name: Build PHP Images
'on':
  push:
    branches:
      - main
jobs:
  build_and_push_php:
    runs-on: ubuntu-latest # 依赖的环境
    strategy:
      matrix:
        version:
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
          - '8.3'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: 'Build and push ${{ matrix.version }}-cli'
        uses: docker/build-push-action@v4
        with:
          context: './php/${{ matrix.version }}-cli'
          push: true
          tags: |
            jkobe824/php-image:${{ matrix.version }}-cli
      - name: 'Build and push ${{ matrix.version }}-fpm'
        uses: docker/build-push-action@v4
        with:
          context: './php/${{ matrix.version }}-fpm'
          push: true
          tags: |
            jkobe824/php-image:${{ matrix.version }}-fpm
